---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-smoke
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-smoke:sha256-513d667a8caf342cd5e3958701fa88e1f987010dee0fbf92b8ddf496e1926212
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: smoke
  name: performance-benchmark-smoke
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting smoke test at $(date)"

              k6 run --out json=/results/smoke-test.json /tests/health-check.js

              echo "Smoke test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: health-check.js
                path: health-check.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-load
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-load:sha256-e412464826dc1eadd7c1f2a279138a1e75168b7d206a55cf24305f1f15af3999
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: load
  name: performance-benchmark-load
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting load test at $(date)"

              k6 run --out json=/results/load-test.json /tests/api-load-test.js

              echo "Load test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: api-load-test.js
                path: api-load-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-stress
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-stress:sha256-abfef3eebc2dde828227235c29b10e0de4e71fbf5b2c37368737879db9b1aa3e
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: stress
  name: performance-benchmark-stress
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting stress test at $(date)"

              k6 run --out json=/results/stress-test.json /tests/stress-test.js

              echo "Stress test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: stress-test.js
                path: stress-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 2
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-endurance
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-endurance:sha256-5955452c859553de2eaa80cdd2a99851ee57094901a9105955125eee7cf10456
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: endurance
  name: performance-benchmark-endurance
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c - | echo "Starting endurance test at $(date)" k6 run --out json=/results/endurance-test.json
              /tests/memory-leak-test.js echo "Endurance test completed at $(date)"
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: memory-leak-test.js
                path: memory-leak-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 0 * * 0
  successfulJobsHistoryLimit: 1
