apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    # 管理員角色
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, logs, get, *, allow
    p, role:admin, exec, create, */*, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, projects, *, *, allow
    
    # 開發者角色 (只讀 + 同步)
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, action/*, */*, allow
    p, role:developer, clusters, get, *, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, exec, create, */*, allow
    
    # 只讀角色
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, logs, get, */*, allow
    
    # 綁定用戶到角色 (示例)
    # g, your-github-username, role:admin
    # g, your-team, role:developer
  
  # 管理員用戶列表
  admin.enabled: "true"
  
  # OIDC 配置 (可選 - 如果使用 Google/GitHub SSO)
  # url: https://argocd.your-domain.com
  # oidc.config: |
  #   name: Google
  #   issuer: https://accounts.google.com
  #   clientID: $GOOGLE_CLIENT_ID
  #   clientSecret: $GOOGLE_CLIENT_SECRET
  #   requestedScopes: ["openid", "profile", "email"]
