apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eco-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Eco-Base AI Platform Project
  
  # 允許的源代碼倉庫
  sourceRepos:
    - 'https://github.com/YOUR_ORG/eco-base.git'  # 替換為您的倉庫
    - 'https://github.com/indestructibleorg/eco-base.git'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://argoproj.github.io/argo-helm'
  
  # 允許部署的目標集群和命名空間
  destinations:
    - namespace: 'production'
      server: 'https://kubernetes.default.svc'
    - namespace: 'staging'
      server: 'https://kubernetes.default.svc'
    - namespace: 'monitoring'
      server: 'https://kubernetes.default.svc'
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
    - namespace: 'ingress-nginx'
      server: 'https://kubernetes.default.svc'
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  
  # 允許的資源類型 (白名單)
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: DaemonSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: cert-manager.io
      kind: Certificate
  
  # 命名空間級資源
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'rbac.authorization.k8s.io'
      kind: '*'
  
  # 同步窗口 (可選 - 限制部署時間)
  # syncWindows:
  #   - kind: allow
  #     schedule: '0 9 * * 1-5'
  #     duration: 8h
  #     applications:
  #       - '*'
  #     clusters:
  #       - '*'
  #     namespaces:
  #       - 'production'
  
  # 角色訪問控制
  roles:
    - name: admin
      description: Admin access to eco-base project
      policies:
        - p, proj:eco-base:admin, applications, *, eco-base/*, allow
        - p, proj:eco-base:admin, repositories, *, eco-base/*, allow
      groups:
        - your-github-org:admin-team  # 替換為您的團隊
    
    - name: developer
      description: Developer access (sync only)
      policies:
        - p, proj:eco-base:developer, applications, get, eco-base/*, allow
        - p, proj:eco-base:developer, applications, sync, eco-base/*, allow
      groups:
        - your-github-org:developers
  
  # 資源配額限制
  # sourceNamespaces:
  #   - 'argocd'
